
export type Field={name:string;label:string;type?:'text'|'number'|'date'|'textarea'|'select'|'account';required?:boolean;options?:string[]};
export type Mod={title:string;emoji:string;kind:'asset'|'liability'|'utility';desc:string;fields:Field[];cols:string[]};
const f=(name:string,label:string,type:Field['type']='text',required=false,options:string[]=[]):Field=>({name,label,type,required,options});
export const RELATIONS=['Self','Spouse','Daughter','Son','Mother','Father','Sister','Brother','Joint','HUF','Company','Trust','Other'];
export const ACCOUNT_TYPES=['Family','Demat','Bank','Retirement','Property','Loan','Business','Imported','Other'];
const BANKS=['Govt','Axis Bank','ICICI Bank','Other'];
const BROKERS=['HDFC Sky','Kotak Securities','Zerodha','Groww','ICICI Direct','Upstox','Angel One','Other'];
export const MODULES:Record<string,Mod>={
 stocks:{title:'Stocks',emoji:'ST',kind:'asset',desc:'Equity holdings with live prices.',fields:[f('account_name','Account','account'),f('security_name','Company / Security','text',true),f('ticker_symbol','Ticker / Symbol'),f('exchange','Exchange','select',false,['NSE','BSE','NYSE','NASDAQ','Other']),f('category','Sector'),f('quantity','Quantity','number'),f('corporate_action_type','Action','select',false,['','Bonus','Split']),f('corporate_action_ratio','Action Ratio'),f('corporate_action_ex_date','Ex Date','date'),f('ex_base_price','Ex-Day Base Price','number'),f('inv_price','Purchase Price','number'),f('live_price','Current Price','number'),f('day_change','Increase','number'),f('day_low','Day Low','number'),f('day_high','Day High','number'),f('fifty_two_week_low','52 Week Low','number'),f('fifty_two_week_high','52 Week High','number'),f('investment_amount','Investment Amount','number'),f('latest_value','Latest Value','number'),f('purchase_date','Purchase Date','date'),f('broker','Broker','select',false,BROKERS),f('last_synced','Last Synced'),f('notes','Notes','textarea')],cols:['account_name','security_name','ticker_symbol','exchange','quantity','corporate_action_type','corporate_action_ratio','corporate_action_ex_date','ex_base_price','inv_price','live_price','day_change','day_low','day_high','fifty_two_week_low','fifty_two_week_high','invested','latest','gain','gain_pct','last_synced']},
 mutualFunds:{title:'Mutual Funds',emoji:'MF',kind:'asset',desc:'Scheme units, NAV and AMFI code.',fields:[f('account_name','Account','account'),f('security_name','Scheme Name','text',true),f('scheme_code','AMFI Scheme Code'),f('category','Category','select',false,['Equity','Debt','Hybrid','Index','Liquid','International','Other']),f('quantity','Units','number'),f('nav','Average NAV','number'),f('live_nav','Current NAV','number'),f('investment_amount','Investment Amount','number'),f('latest_value','Latest Value','number'),f('purchase_date','Purchase Date','date'),f('broker','AMC / Platform','select',false,BROKERS),f('notes','Notes','textarea')],cols:['account_name','security_name','scheme_code','category','quantity','nav','live_nav','invested','latest','gain','gain_pct']},
 ulips:{title:'ULIPs',emoji:'UL',kind:'asset',desc:'Policy premiums and fund value.',fields:[f('account_name','Account','account'),f('security_name','Policy Name','text',true),f('category','Provider'),f('premium_amount','Premium Amount','number'),f('investment_amount','Total Invested','number'),f('latest_value','Current Fund Value','number'),f('purchase_date','Start Date','date'),f('maturity_date','Maturity Date','date'),f('broker','Agent / Platform'),f('notes','Notes','textarea')],cols:['account_name','security_name','category','premium_amount','invested','latest','gain','maturity_date']},
 bullion:{title:'Bullion',emoji:'GLD',kind:'asset',desc:'Gold and silver with local pricing and landed-cost tracking.',fields:[f('account_name','Account','account'),f('security_name','Metal','text',true),f('quantity','Quantity','number'),f('unit','Unit','select',false,['gms','kg','oz','units']),f('city','Purchase / Pricing City'),f('latitude','Latitude','number'),f('longitude','Longitude','number'),f('local_premium_per_gram','Local Premium per Gram','number'),f('metal_cost','Metal Cost','number'),f('making_charges','Making Charges','number'),f('gst_paid','GST / Tax Paid','number'),f('other_costs','Other Costs','number'),f('purchase_price','Total Landed Cost','number'),f('latest_value','Latest Value','number'),f('purchase_date','Purchase Date','date'),f('broker','Dealer / Vault / Source'),f('notes','Notes','textarea')],cols:['account_name','security_name','city','quantity','unit','current_price','today_gain','invested','latest','gain','gain_pct']},
 nsel:{title:'NSEL e-Series',emoji:'NS',kind:'asset',desc:'e-Gold/e-Silver holdings.',fields:[f('account_name','Account','account'),f('security_name','Instrument','select',true,['e-Gold','e-Silver','e-Platinum','Other']),f('quantity','Quantity','number'),f('unit','Unit','select',false,['units','gms','kg']),f('purchase_price','Purchase / Invested Value','number'),f('latest_value','Latest Value','number'),f('purchase_date','Purchase Date','date'),f('broker','Depository'),f('notes','Notes','textarea')],cols:['account_name','security_name','quantity','unit','invested','latest','gain','gain_pct']},
fixedIncome:{title:'Fixed Income',emoji:'FI',kind:'asset',desc:'FD, RD, PPF, Sukanya, Company PF, gratuity, bonds and deposits.',fields:[f('account_name','Account','account'),f('category','Type','select',false,['FD','Recurring Deposit','PPF','Sukanya Samriddhi','Bond','NSC','KVP','EPF','Company PF','Gratuity','Corporate Deposit','Other']),f('purchase_date','Start Date','date'),f('account_creation_date','Account Creation Date','date'),f('interest_rate','Int. Rate','number'),f('rate_year','Rate Year / FY'),f('lock_in_years','Lock-in Years','number'),f('employee_contribution','Monthly Contribution by Employee','number'),f('company_contribution','Monthly Contribution by Employer','number'),f('gratuity_value','Gratuity Value','number'),f('maturity_value','Total Maturity Value','number'),f('current_value_today','Value Before FY Interest','number'),f('maturity_date','Maturity Date','date'),f('broker','Institution','select',false,BANKS),f('notes','Notes','textarea')],cols:['account_name','category','employee_contribution','company_contribution','broker','purchase_date','interest_rate','current_value_today','interest_incurred_fy','latest','year_end_maturity_value','maturity_value','maturity_date']},
 insurance:{title:'Insurance',emoji:'IN',kind:'utility',desc:'Term plans and family protection cover.',fields:[f('account_name','Account / Life Insured','account'),f('security_name','Policy Name','text',true),f('category','Policy Type','select',false,['Term Plan','Health Insurance','Critical Illness','Accident Cover','Other']),f('sum_assured','Sum Assured','number'),f('payout_value','Payout Value','number'),f('current_value_including_bonus','Current Value Including Bonus','number'),f('annual_premium','Annual Premium','number'),f('premium_due_date','Premium Due Date','date'),f('policy_start_date','Policy Start Date','date'),f('policy_end_date','Policy End Date','date'),f('nominee','Nominee'),f('status','Status','select',false,['Active','Grace Period','Lapsed','Closed']),f('death_cover_after_closure','Death Cover After Closure?','select',false,['Yes','No']),f('broker','Insurer / Platform'),f('notes','Notes','textarea')],cols:['account_name','category','security_name','broker','status','policy_start_date','annual_premium','policy_years_paid','premiums_paid_to_date','yearly_bonus','lic_bonus','latest','death_cover_after_closure','death_cover_value']},
 property:{title:'Property',emoji:'PR',kind:'asset',desc:'Real estate assets with loan future details.',fields:[f('account_name','Account','account'),f('security_name','Property Type','select',true,['Residential','Commercial','Land','Plot','Other']),f('category','Usage / Status'),f('location','Location'),f('purchase_price','Purchase Price','number'),f('latest_value','Latest Value','number'),f('purchase_date','Purchase Date','date'),f('loan_amount','Loan Amount','number'),f('loan_interest_rate','Loan Interest Rate %','number'),f('loan_tenure_months','Loan Tenure Months','number'),f('principal_paid','Principal Paid','number'),f('interest_paid','Interest Paid','number'),f('loan_balance','Current Loan Balance','number'),f('emis_left','EMIs Left','number'),f('broker','Community'),f('notes','Notes','textarea')],cols:['account_name','security_name','location','broker','invested','latest','gain','loan_amount','loan_balance','loan_interest_rate','emis_left','emiFuture']},
 otherAssets:{title:'Other Assets',emoji:'OA',kind:'asset',desc:'Other portfolio items.',fields:[f('account_name','Account','account'),f('security_name','Asset Name','text',true),f('category','Category'),f('purchase_price','Invested Value','number'),f('latest_value','Latest Value','number'),f('purchase_date','Purchase Date','date'),f('broker','Source'),f('notes','Notes','textarea')],cols:['account_name','security_name','category','invested','latest','gain','gain_pct']},
 loans:{title:'Loans',emoji:'LN',kind:'liability',desc:'Home, personal and business loans.',fields:[f('account_name','Account','account'),f('security_name','Loan Type','select',true,['Home','Personal','Vehicle','Business','Education','Other']),f('loan_amount','Loan Amount','number'),f('interest_rate','Interest Rate %','number'),f('tenure_months','Tenure Months','number'),f('principal_paid','Principal Paid','number'),f('interest_paid','Interest Paid','number'),f('loan_balance','Current Loan Balance','number'),f('emis_left','EMIs Left','number'),f('purchase_date','Start Date','date'),f('broker','Bank / Lender'),f('notes','Notes','textarea')],cols:['account_name','security_name','loan_amount','principal_paid','interest_paid','balance','emis_left','interest_rate']},
 borrowings:{title:'Borrowings',emoji:'BR',kind:'liability',desc:'Other liabilities.',fields:[f('account_name','Account','account'),f('security_name','Borrowing Name','text',true),f('category','Type'),f('loan_amount','Amount','number'),f('interest_rate','Rate %','number'),f('principal_paid','Amount Paid','number'),f('interest_paid','Interest Paid','number'),f('loan_balance','Outstanding Balance','number'),f('purchase_date','Start Date','date'),f('broker','Lender'),f('notes','Notes','textarea')],cols:['account_name','security_name','category','loan_amount','principal_paid','balance','interest_rate']},
 goals:{title:'Goals',emoji:'GO',kind:'utility',desc:'Education, retirement and reserve goals.',fields:[f('account_name','Owner / Account','account'),f('security_name','Goal Name','text',true),f('category','Goal Type','select',false,['Education','Retirement','Emergency Fund','Property','Medical Reserve','Debt Free','Other']),f('target_amount','Target Amount','number'),f('current_value','Current Value','number'),f('target_date','Target Date','date'),f('priority','Priority','select',false,['High','Medium','Low']),f('notes','Notes','textarea')],cols:['account_name','category','security_name','target_amount','current_value','gap','monthly_required','target_date']},
 watchlist:{title:'Watchlist',emoji:'WL',kind:'utility',desc:'Stock watchlist ideas with live prices and gains.',fields:[f('security_name','Company / Security','text',true),f('ticker_symbol','Ticker / Symbol'),f('exchange','Exchange','select',false,['NSE','BSE','NYSE','NASDAQ','Other']),f('category','Sector'),f('quantity','Quantity','number'),f('base_price','Added Price','number'),f('base_price_date','Date Added','date'),f('inv_price','Investment Price','number'),f('current_price','Current Price','number'),f('previous_close','Previous Close','number'),f('day_change','Change','number'),f('target_price','Target Price','number'),f('notes','Notes','textarea')],cols:['security_name','ticker_symbol','exchange','category','quantity','base_price_date','base_price','current_price','day_change','target_price']},
 alerts:{title:'Alerts',emoji:'AL',kind:'utility',desc:'Reminder and review items.',fields:[f('security_name','Alert Title','text',true),f('category','Type','select',false,['Review','Payment','Maturity','Renewal','Insurance','Tax','Other']),f('due_date','Due Date','date'),f('priority','Priority','select',false,['High','Medium','Low']),f('status','Status','select',false,['Open','Done','Deferred']),f('notes','Notes','textarea')],cols:['due_date','priority','status','category','security_name']}
};
export const moduleKeys=Object.keys(MODULES);

