
export type Field={name:string;label:string;type?:'text'|'number'|'date'|'textarea'|'select'|'account';required?:boolean;options?:string[]};
export type Mod={title:string;emoji:string;kind:'asset'|'liability'|'utility';desc:string;fields:Field[];cols:string[]};
const f=(name:string,label:string,type:Field['type']='text',required=false,options:string[]=[]):Field=>({name,label,type,required,options});
export const RELATIONS=['Self','Spouse','Daughter','Son','Mother','Father','Sister','Brother','Joint','HUF','Company','Trust','Other'];
export const ACCOUNT_TYPES=['Family','Demat','Bank','Retirement','Property','Loan','Business','Imported','Other'];
const BANKS=['Govt','Axis Bank','ICICI Bank','Other'];
const BROKERS=['HDFC Sky','Kotak Securities','Zerodha','Groww','ICICI Direct','Upstox','Angel One','Other'];
export const MODULES:Record<string,Mod>={
 stocks:{title:'Stocks',emoji:'ST',kind:'asset',desc:'Equity holdings with live prices.',fields:[f('account_name','Account','account'),f('security_name','Company / Security','text',true),f('ticker_symbol','Ticker / Symbol'),f('exchange','Exchange','select',false,['NSE','BSE','NYSE','NASDAQ','Other']),f('category','Sector'),f('quantity','Quantity','number'),f('corporate_action_type','Action','select',false,['','Bonus','Split']),f('corporate_action_ratio','Action Ratio'),f('corporate_action_ex_date','Ex Date','date'),f('ex_base_price','Ex-Day Base Price','number'),f('inv_price','Purchase Price','number'),f('live_price','Current Price','number'),f('day_change','Increase','number'),f('day_low','Day Low','number'),f('day_high','Day High','number'),f('fifty_two_week_low','52 Week Low','number'),f('fifty_two_week_high','52 Week High','number'),f('investment_amount','Investment Amount','number'),f('latest_value','Latest Value','number'),f('purchase_date','Purchase Date','date'),f('broker','Broker','select',false,BROKERS),f('last_synced','Last Synced'),f('notes','Notes','textarea')],cols:['account_name','security_name','ticker_symbol','exchange','quantity','corporate_action_type','corporate_action_ratio','corporate_action_ex_date','ex_base_price','inv_price','live_price','day_change','day_low','day_high','fifty_two_week_low','fifty_two_week_high','invested','latest','gain','gain_pct','last_synced']},
 mutualFunds:{title:'Mutual Funds',emoji:'MF',kind:'asset',desc:'Scheme units, NAV and AMFI code.',fields:[f('account_name','Account','account'),f('security_name','Scheme Name','text',true),f('scheme_code','AMFI Scheme Code'),f('category','Category','select',false,['Equity','Debt','Hybrid','Index','Liquid','International','Other']),f('quantity','Units','number'),f('nav','Average NAV','number'),f('live_nav','Current NAV','number'),f('investment_amount','Investment Amount','number'),f('latest_value','Latest Value','number'),f('purchase_date','Purchase Date','date'),f('broker','AMC / Platform','select',false,BROKERS),f('notes','Notes','textarea')],cols:['account_name','security_name','scheme_code','category','quantity','nav','live_nav','invested','latest','gain','gain_pct']},
 ulips:{title:'ULIPs',emoji:'UL',kind:'asset',desc:'Policy premiums and fund value.',fields:[f('account_name','Account','account'),f('security_name','Policy Name','text',true),f('category','Provider'),f('premium_amount','Premium Amount','number'),f('investment_amount','Total Invested','number'),f('latest_value','Current Fund Value','number'),f('purchase_date','Start Date','date'),f('maturity_date','Maturity Date','date'),f('broker','Agent / Platform'),f('notes','Notes','textarea')],cols:['account_name','security_name','category','premium_amount','invested','latest','gain','maturity_date']},
 bullion:{title:'Bullion',emoji:'GLD',kind:'asset',desc:'Gold and silver with local pricing and landed-cost tracking.',fields:[f('account_name','Account','account'),f('security_name','Metal','text',true),f('quantity','Quantity','number'),f('unit','Unit','select',false,['gms','kg','oz','units']),f('city','Purchase / Pricing City'),f('latitude','Latitude','number'),f('longitude','Longitude','number'),f('local_premium_per_gram','Local Premium per Gram','number'),f('metal_cost','Metal Cost','number'),f('making_charges','Making Charges','number'),f('gst_paid','GST / Tax Paid','number'),f('other_costs','Other Costs','number'),f('purchase_price','Total Landed Cost','number'),f('latest_value','Latest Value','number'),f('purchase_date','Purchase Date','date'),f('broker','Dealer / Vault / Source'),f('notes','Notes','textarea')],cols:['account_name','security_name','city','quantity','unit','current_price','today_gain','invested','latest','gain','gain_pct']},
 nsel:{title:'NSEL e-Series',emoji:'NS',kind:'asset',desc:'e-Gold/e-Silver holdings.',fields:[f('account_name','Account','account'),f('security_name','Instrument','select',true,['e-Gold','e-Silver','e-Platinum','Other']),f('quantity','Quantity','number'),f('unit','Unit','select',false,['units','gms','kg']),f('purchase_price','Purchase / Invested Value','number'),f('latest_value','Latest Value','number'),f('purchase_date','Purchase Date','date'),f('broker','Depository'),f('notes','Notes','textarea')],cols:['account_name','security_name','quantity','unit','invested','latest','gain','gain_pct']},
fixedIncome:{title:'Fixed Income',emoji:'FI',kind:'asset',desc:'Salary, rental income, FD, RD, PPF, Sukanya, Company PF, gratuity, bonds and deposits.',fields:[f('account_name','Account','account'),f('category','Type','select',false,['Salary','Rental Income','FD','Recurring Deposit','PPF','Sukanya Samriddhi','Bond','NSC','KVP','EPF','Company PF','Gratuity','Corporate Deposit','Other']),f('purchase_date','Start Date','date'),f('last_working_date','Last Working Date / Calculation Date','date'),f('monthly_basic_salary','Monthly Basic Salary','number'),f('monthly_da','Monthly DA (Optional)','number'),f('covered_under_gratuity_act','Covered under Payment of Gratuity Act?','select',false,['Yes','No']),f('account_creation_date','Account Creation Date','date'),f('interest_rate','Int. Rate','number'),f('rate_year','Rate Year / FY'),f('lock_in_years','Lock-in Years','number'),f('employee_contribution','Monthly Contribution by Employee','number'),f('company_contribution','Monthly Contribution by Employer','number'),f('yearly_investment','Yearly Investment / Deposit','number'),f('gratuity_value','Gratuity Value','number'),f('maturity_value','Total Maturity Value','number'),f('current_value_today','Value Before FY Interest','number'),f('maturity_date','Maturity Date','date'),f('rentee_name','Rentee Name'),f('rentee_phone','Rentee Phone'),f('rent_agreement_start_date','Agreement Start Date','date'),f('broker','Institution','select',false,BANKS),f('notes','Notes','textarea')],cols:['account_name','category','employee_contribution','company_contribution','yearly_investment','broker','purchase_date','interest_rate','current_value_today','interest_incurred_fy','latest','year_end_maturity_value','maturity_value','maturity_date','yearly_total_value']},
 insurance:{title:'Insurance',emoji:'IN',kind:'utility',desc:'Life, health and protection policies with type-specific cover and value calculations.',fields:[
  f('account_name','Account','account'),f('life_insured','Life Insured'),f('security_name','Policy Name','text',true),
  f('category','Policy Type','select',true,['Term Plan','Health Insurance','Life Insurance','Endowment / LIC','Money Back','ULIP','Accident Cover','Critical Illness','Other']),
  f('broker','Insurer','text',true),f('insurance_broker','Broker / Agent'),f('status','Status','select',true,['Active','Lapsed','Closed','Paid-up','Matured']),
  f('policy_start_date','Policy Start Date','date'),f('policy_end_date','Policy / Cover End Date','date'),f('cover_end_date','Cover End Date','date'),
  f('premium_amount','Premium Amount','number'),f('premium_frequency','Premium Frequency','select',false,['Monthly','Quarterly','Half-yearly','Yearly','Single']),
  f('premium_paying_term_type','Premium Paying Term','select',false,['Single Pay','Limited Years','Until Age','Till Maturity']),
  f('premium_paying_years','Premium Paying Years','number'),f('premium_paying_till_age','Premium Paying Till Age','number'),f('premium_end_date','Premium End Date','date'),
  f('premium_due_date','Next Premium Due Date','date'),f('premium_years_paid','Premium Years Paid','number'),f('single_premium_paid','Single Premium Paid?','select',false,['Yes','No']),
  f('sum_assured','Sum Assured','number'),f('additional_rider_cover','Additional Rider Cover','number'),f('return_of_premium','Return of Premium?','select',false,['Yes','No']),
  f('covered_members','Covered Members','textarea'),f('base_health_cover','Base Health Cover','number'),f('super_topup_cover','Super Top-up Cover','number'),f('no_claim_bonus','No Claim Bonus','number'),
  f('deductible','Deductible','number'),f('co_pay','Co-pay %','number'),f('room_rent_limit','Room Rent Limit'),f('waiting_period','Waiting Period'),
  f('accidental_death_cover','Accidental Death Cover','number'),f('permanent_disability_cover','Permanent Disability Cover','number'),f('temporary_disability_cover','Temporary Disability Cover','number'),
  f('critical_illness_cover','Critical Illness Cover','number'),f('covered_illnesses','Covered Illnesses','textarea'),f('survival_period','Survival Period'),
  f('maturity_sum_assured','Maturity Sum Assured','number'),f('bonus_rate','Bonus Rate %','number'),f('bonus_accrued_till_date','Bonus Accrued Till Date','number'),f('final_additional_bonus','Final Additional Bonus','number'),
  f('money_back_received','Money Back Received','number'),f('next_money_back_date','Next Money Back Date','date'),f('next_money_back_amount','Next Money Back Amount','number'),
  f('surrender_value','Surrender Value','number'),f('current_value','Current Value','number'),f('maturity_value','Maturity Value','number'),
  f('fund_value','Fund Value','number'),f('units','Units','number'),f('nav','NAV','number'),
  f('death_cover_after_premium_closure','Death Cover After Premium Closure?','select',false,['Yes','No']),f('benefits_continue_after_maturity','Benefits Continue After Maturity?','select',false,['Yes','No']),
  f('nominee','Nominee'),f('notes','Notes','textarea')
 ],cols:['account_name','category','security_name','broker','status','annual_premium','premium_frequency','premium_years_paid','premium_end_date','policy_end_date','death_cover','latest','bonus_accrued_till_date','money_back_received','maturity_value','next_premium_due_date','nominee']},
 property:{title:'Property',emoji:'PR',kind:'asset',desc:'Real estate assets with loan future details.',fields:[f('account_name','Account','account'),f('security_name','Property Type','select',true,['Residential','Commercial','Land','Plot','Other']),f('category','Usage / Status'),f('location','Location'),f('purchase_price','Purchase Price','number'),f('latest_value','Latest Value','number'),f('purchase_date','Purchase Date','date'),f('loan_amount','Loan Amount','number'),f('loan_interest_rate','Loan Interest Rate %','number'),f('loan_tenure_months','Loan Tenure Months','number'),f('principal_paid','Principal Paid','number'),f('interest_paid','Interest Paid','number'),f('loan_balance','Current Loan Balance','number'),f('emis_left','EMIs Left','number'),f('is_rented','Is this rented out?','select',false,['No','Yes']),f('monthly_rent','Monthly Rent','number'),f('rentee_name','Rentee Name'),f('rentee_phone','Rentee Phone'),f('rent_agreement_start_date','Agreement Start Date','date'),f('rent_agreement_end_date','Agreement End Date','date'),f('broker','Community'),f('notes','Notes','textarea')],cols:['account_name','security_name','location','broker','invested','latest','gain','loan_amount','loan_balance','loan_interest_rate','emis_left','emiFuture','is_rented','monthly_rent','rentee_name','rentee_phone','rent_agreement_start_date','rent_agreement_end_date']},
 otherAssets:{title:'Other Assets',emoji:'OA',kind:'asset',desc:'Other portfolio items.',fields:[f('account_name','Account','account'),f('security_name','Asset Name','text',true),f('category','Category'),f('purchase_price','Invested Value','number'),f('latest_value','Latest Value','number'),f('purchase_date','Purchase Date','date'),f('broker','Source'),f('notes','Notes','textarea')],cols:['account_name','security_name','category','invested','latest','gain','gain_pct']},
 loans:{title:'Loans',emoji:'LN',kind:'liability',desc:'Home, personal and business loans.',fields:[f('account_name','Account','account'),f('security_name','Loan Type','select',true,['Home','Personal','Vehicle','Business','Education','Other']),f('loan_amount','Loan Amount','number'),f('interest_rate','Interest Rate %','number'),f('tenure_months','Tenure Months','number'),f('principal_paid','Principal Paid','number'),f('interest_paid','Interest Paid','number'),f('loan_balance','Current Loan Balance','number'),f('emis_left','EMIs Left','number'),f('purchase_date','Start Date','date'),f('broker','Bank / Lender'),f('notes','Notes','textarea')],cols:['account_name','security_name','loan_amount','principal_paid','interest_paid','balance','emis_left','interest_rate']},
 borrowings:{title:'Borrowings',emoji:'BR',kind:'liability',desc:'Other liabilities.',fields:[f('account_name','Account','account'),f('security_name','Borrowing Name','text',true),f('category','Type'),f('loan_amount','Amount','number'),f('interest_rate','Rate %','number'),f('principal_paid','Amount Paid','number'),f('interest_paid','Interest Paid','number'),f('loan_balance','Outstanding Balance','number'),f('purchase_date','Start Date','date'),f('broker','Lender'),f('notes','Notes','textarea')],cols:['account_name','security_name','category','loan_amount','principal_paid','balance','interest_rate']},
 goals:{title:'Goals',emoji:'GO',kind:'utility',desc:'Education, retirement and reserve goals.',fields:[f('account_name','Owner / Account','account'),f('security_name','Goal Name','text',true),f('category','Goal Type','select',false,['Education','Retirement','Emergency Fund','Property','Medical Reserve','Debt Free','Other']),f('target_amount','Target Amount','number'),f('current_value','Current Value','number'),f('target_date','Target Date','date'),f('priority','Priority','select',false,['High','Medium','Low']),f('notes','Notes','textarea')],cols:['account_name','category','security_name','target_amount','current_value','gap','monthly_required','target_date']},
 watchlist:{title:'Watchlist',emoji:'WL',kind:'utility',desc:'Stock watchlist ideas with live prices and gains.',fields:[f('security_name','Company / Security','text',true),f('ticker_symbol','Ticker / Symbol'),f('exchange','Exchange','select',false,['NSE','BSE','NYSE','NASDAQ','Other']),f('category','Sector'),f('quantity','Quantity','number'),f('base_price','Added Price','number'),f('base_price_date','Date Added','date'),f('inv_price','Investment Price','number'),f('current_price','Current Price','number'),f('previous_close','Previous Close','number'),f('day_change','Change','number'),f('target_price','Target Price','number'),f('notes','Notes','textarea')],cols:['security_name','ticker_symbol','exchange','category','quantity','base_price_date','base_price','current_price','day_change','target_price']},
 alerts:{title:'Alerts',emoji:'AL',kind:'utility',desc:'Reminder and review items.',fields:[f('security_name','Alert Title','text',true),f('category','Type','select',false,['Review','Payment','Maturity','Renewal','Insurance','Tax','Other']),f('due_date','Due Date','date'),f('priority','Priority','select',false,['High','Medium','Low']),f('status','Status','select',false,['Open','Done','Deferred']),f('notes','Notes','textarea')],cols:['due_date','priority','status','category','security_name']}
};
MODULES.stocks.title='Stocks & ETFs';
MODULES.stocks.desc='Stock and ETF holdings with live prices.';
MODULES.stocks.fields.splice(1,0,f('asset_type','Asset Type','select',false,['Stock','ETF']));
MODULES.stocks.cols.splice(1,0,'asset_type');
MODULES.watchlist.desc='Stock and ETF watchlist ideas with live prices and gains.';
MODULES.watchlist.fields.unshift(f('asset_type','Asset Type','select',false,['Stock','ETF']));
MODULES.watchlist.cols.unshift('asset_type');
export const moduleKeys=Object.keys(MODULES);

