// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/iphone-preview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/iphone-preview">> = Specific
  const handler = {} as typeof import("../../app/iphone-preview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/mobile-preview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mobile-preview">> = Specific
  const handler = {} as typeof import("../../app/mobile-preview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users">> = Specific
  const handler = {} as typeof import("../../app/api/admin/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ai-advisor/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai-advisor">> = Specific
  const handler = {} as typeof import("../../app/api/ai-advisor/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/documents/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/documents">> = Specific
  const handler = {} as typeof import("../../app/api/documents/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/fixed-income-defaults/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/fixed-income-defaults">> = Specific
  const handler = {} as typeof import("../../app/api/fixed-income-defaults/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/google-drive/auth-url/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/google-drive/auth-url">> = Specific
  const handler = {} as typeof import("../../app/api/google-drive/auth-url/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/google-drive/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/google-drive/callback">> = Specific
  const handler = {} as typeof import("../../app/api/google-drive/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/google-drive/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/google-drive/status">> = Specific
  const handler = {} as typeof import("../../app/api/google-drive/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/market-rate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/market-rate">> = Specific
  const handler = {} as typeof import("../../app/api/market-rate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/market-trend/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/market-trend">> = Specific
  const handler = {} as typeof import("../../app/api/market-trend/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/moneycontrol-commodity/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/moneycontrol-commodity">> = Specific
  const handler = {} as typeof import("../../app/api/moneycontrol-commodity/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/moneycontrol-detail/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/moneycontrol-detail">> = Specific
  const handler = {} as typeof import("../../app/api/moneycontrol-detail/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/nav/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/nav">> = Specific
  const handler = {} as typeof import("../../app/api/nav/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/quote/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/quote">> = Specific
  const handler = {} as typeof import("../../app/api/quote/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/stock-search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stock-search">> = Specific
  const handler = {} as typeof import("../../app/api/stock-search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
